### PR TITLE
Update leaderelection.adoc

### PR DESCRIPTION
**Pull request by sprgn**
Fix some typos.

### CODE REVIEW

**Comment by pperalta** [comment]
Thank you for your contribution! Have you signed the Individual Contributor Agreement? This is a requirement for us to accept pull requests from contributors:

https://support.springsource.com/spring_committer_signup

Thanks,
Patrick

**Comment by sprgn** [comment]
Patrick, do I list you as the project lead on that signup form?

Thanks,
Alex

**Comment by spencergibb** [comment]
@sprgn yes or Dave Syer

**Comment by pperalta** [comment]
Rebased and merged as c0fe1e8

**Pull request closed without merging**
